# Generated by Django 6.0.2 on 2026-02-17 13:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_habit_frequency_habit_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
