# Generated by Django 6.0.2 on 2026-02-19 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_habit_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='target_amount',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='habit',
            name='unit',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='HabitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount_done', models.PositiveIntegerField(default=0)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='habits.habit')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('habit', 'date')},
            },
        ),
    ]
